services:
  db:
    image: mariadb:10.5
    container_name: rathena-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok
    volumes:
      - db_data:/var/lib/mysql
    networks:
      rathena-network:
        aliases:
          - db

  rathena:
    build: .
    container_name: rathena-server
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ragnarok
      MYSQL_PASS: ragnarok
      MYSQL_DB: ragnarok
      SERVER_MODE: local
      INTERSERVER_USER: s1
      INTERSERVER_PASS: p1
    ports:
      - "6900:6900"  # Login Server
      - "6121:6121"  # Char Server
      - "5121:5121"  # Map Server
      - "8888:8888"  # Web Server
    volumes:
      - ./log:/home/rathena/rAthena/log
    networks:
      rathena-network:
        aliases:
          - rathena

networks:
  rathena-network:
    driver: bridge

volumes:
  db_data: