services:
  db:
    image: mariadb:10.5
    container_name: rathena-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rathena-network

  rathena:
    build: .
    container_name: rathena-server
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ragnarok
      MYSQL_PASS: ragnarok
      MYSQL_DB: ragnarok
      SERVER_MODE: local    # Modo de operação do servidor (local/production)
      INTERSERVER_USER: s1  # Usuário para comunicação entre servidores
      INTERSERVER_PASS: p1  # Senha para comunicação entre servidores
    ports:
      - "6900:6900"  # Login Server
      - "6121:6121"  # Char Server
      - "5121:5121"  # Map Server
      - "8888:8888"  # Web Server
    volumes:
      # Para desenvolvimento, use bind mounts
      # - ./conf:/home/rathena/rAthena/conf # Comentado para usar configurações internas primeiro
      - ./log:/home/rathena/rAthena/log
      # - ./npc:/home/rathena/rAthena/npc # Comentado para usar NPCs internos primeiro
      # - ./db:/home/rathena/rAthena/db # Comentado para usar DBs internos primeiro
    networks:
      - rathena-network

networks:
  rathena-network:
    driver: bridge

volumes:
  db_data: